### ISSUE TITLE
[Language Request] Lua

### ISSUE THREAD

**Issue by Stanzilla** [georgewfraser/vscode-tree-sitter#1]
I have no real experience with this, but would it be possible to craft Lua support from an existing project like https://github.com/oxyc/luaparse?

**Comment by georgewfraser** [comment]
In order to add support for Lua, you would first need to write a tree-sitter grammar for Lua. According to the [home page](https://tree-sitter.github.io/tree-sitter/), there isn't one yet.

**Comment by Stanzilla** [comment]
@georgewfraser How about https://github.com/Azganoth/tree-sitter-lua?
