### ISSUE TITLE
[Bug] Highlighting don't work

### ISSUE THREAD

**Issue by olvyko** [georgewfraser/vscode-tree-sitter#13]
After version of `tree sitter` was changed to the wasm, the extension stopped working.
I have this errors:
![tree-sitter-errors-2](https://user-images.githubusercontent.com/44478988/58302847-7ed32a00-7ded-11e9-9036-5cf1372f81c1.png)

**Comment by georgewfraser** [comment]
I think this might be https://github.com/tree-sitter/tree-sitter/issues/338

**Comment by georgewfraser** [comment]
I've published a workaround---converting to relative paths. Thanks for reporting!
