### ISSUE TITLE
[Language request] Rust

### ISSUE THREAD

**Issue by Geobert** [georgewfraser/vscode-tree-sitter#2]
How can we introduce Rust support?

**Comment by georgewfraser** [comment]
Done!

<img width="1236" alt="rust" src="https://user-images.githubusercontent.com/1369240/57988866-00226980-7a48-11e9-8990-995292c30448.png">

**Comment by Geobert** [comment]
Too bad I'm on Windows ^^' (I've suscribed to the relevant issue)
