### ISSUE TITLE
Does not work on vscode remote ssh in rust

### ISSUE THREAD

**Issue by kigawas** [georgewfraser/vscode-tree-sitter#23]

**Comment by ztlpn** [comment]
Changing the extension kind to `ui` as documented [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) fixed the issue for me.

This can be done by the user:
1. Uninstall the extension on the remote host and install it locally
2. Add the following to `settings.json`:
```
{
    "remote.extensionKind": {
        "georgewfraser.vscode-tree-sitter": "ui"
    }
}
```
3. Reload VSCode

And probably should be done in `package.json`.
