### ISSUE TITLE
I ran the Extension Bisect early today and it gave me this result that yesterday didn't got any feedback

### ISSUE THREAD

**Issue by OOOHA** [georgewfraser/vscode-tree-sitter#35]
Issue Type: <b>Bug</b>

The same issue from my report [#118401](https://github.com/microsoft/vscode/issues/118401#issue-824186538) and at that time I ran the Extension Bisec it saied it's all fine.
Since I can't even use VSCode anymore, I decided to run Extension Bisect again and it gave me this report.

Extension version: 0.1.26
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 3|
|Memory (System)|8.00GB (1.23GB free)|
|Process Argv|--crash-reporter-id 3f12e0b1-128d-4528-9fb3-29fc2b9c754f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by georgewfraser** [comment]
vscode-tree-sitter is no longer maintained, it's been obviated by semantic coloring.

**Comment by OOOHA** [comment]
The issue is no longer exists in the latest version.
